# Generated by Django 5.1.2 on 2024-11-19 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0002_classification_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='Classification_Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Classification_Owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='Show_Owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Show_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
