# Generated by Django 5.1.2 on 2024-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0003_alter_classification_classification_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Show_Classification',
            field=models.ManyToManyField(related_name='Show_Classification', to='WatchingHub.classification'),
        ),
    ]
