# Generated by Django 5.1.2 on 2024-11-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0007_alter_show_publication_year_alter_show_show_raring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Date_finished_watching',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
