# Generated by Django 5.1.2 on 2024-11-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0008_alter_show_date_finished_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Date_finished_watching',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Publication_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='Show_raring',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
