# Generated by Django 5.1.2 on 2024-11-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0009_alter_show_date_finished_watching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='duration',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
