# Generated by Django 5.1.2 on 2024-12-13 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0010_alter_show_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort_Shows_By', models.CharField(choices=[('Random', 'Random'), ('Date_finished_watching', 'Date Finished Watching'), ('Publication_year', 'Publication Year'), ('Show_Classification', 'Show Classification'), ('Show_Owner', 'Show Owner'), ('Show_raring', 'Show Rating'), ('Show_title', 'Show Title')], default='Random', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
