# Generated by Django 5.1.2 on 2024-12-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0011_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Sort_Shows_By',
            field=models.CharField(choices=[('Random', 'Random'), ('Date_finished_watching', 'Date Finished Watching'), ('Publication_year', 'Publication Year'), ('Show_Classification', 'Show Classification'), ('Show_Owner', 'Show Owner'), ('Show_raring', 'Show Rating'), ('Show_title', 'Show Title')], max_length=50),
        ),
    ]
