# Generated by Django 5.1.2 on 2024-12-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WatchingHub', '0014_alter_settings_sort_shows_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='Sort_Shows_By',
            field=models.CharField(choices=[('Random', 'Random'), ('Show_title', 'Show Title'), ('Date_added_latest', 'Date Added (Latest First)'), ('Date_added_oldest', 'Date Added (Oldest First)'), ('Newest_in_release', 'Newest in Release'), ('Oldest_in_release', 'Oldest in Release'), ('Highest_rating', 'Highest Rating'), ('Lowest_rating', 'Lowest Rating'), ('Date_finished_watching_latest', 'Date Finished Watching (Latest First)'), ('Date_finished_watching_oldest', 'Date Finished Watching (Oldest First)'), ('Longest_duration', 'Longest Duration'), ('Shortest_duration', 'Shortest Duration')], max_length=50),
        ),
    ]
